language: python
python:
  - 2.7
before_install:
  - sudo apt-get install python-dev libgmp3-dev
install:
  - pip install pep8
before_script:
  - pep8 --max-line-length=1000 --ignore=E402 */*.py
  - python setup.py install
script:
  - python fastecdsa/test.py
