language: python
python:
  - 2.7
before_install:
  - sudo apt-get install python-dev libgmp3-dev
install:
  - pip install pep8 coveralls
before_script:
  - pep8 --max-line-length=200 --ignore=E402 */*.py
  - pip install -e .
script:
  coverage run --source=fastecdsa setup.py test
after_success:
  coveralls
